const agentUrl = process.env.NEXT_PUBLIC_AGENT_API_URL ? new URL(process.env.NEXT_PUBLIC_AGENT_API_URL) : null

/** @type {import('next').NextConfig} */
const nextConfig = {
	outputFileTracingRoot: process.cwd(),
	images: {
		remotePatterns: [
			// QR transfer images are generated by the configured Tagroot partner
			// host (for example athletesandyou.tagroot.io). Limit this wildcard to
			// the QR endpoint instead of allowing arbitrary partner-host images.
			{
				protocol: 'https',
				hostname: '**.tagroot.io',
				port: '',
				pathname: '/QR/**',
			},
			...(agentUrl ? [{
				protocol: agentUrl.protocol.slice(0, -1),
				hostname: agentUrl.hostname,
				port: agentUrl.port,
				pathname: '/**',
			}] : []),
		],
	},
}
export default nextConfig
