const SCENARIOS = Object.freeze({
  'details': { step: 3, durable: true, phoneVerified: true, emailVerified: true },
  'account-loading': { step: 0, ui: 'account-loading' },
  'phone-otp': { step: 1 },
  'phone-error': { step: 1, ui: 'otp-error' },
  'email-otp': { step: 2, phoneVerified: true },
  'email-error': { step: 2, phoneVerified: true, ui: 'otp-error' },
  'front-empty': { step: 11, durable: true },
  'device-front': { step: 11, deviceTest: true },
  'device-selfie': { step: 14, frontPhoto: true, backPhoto: true, deviceTest: true },
  'front-saving': { step: 11, durable: true, ui: 'saving' },
  'front-failed': { step: 11, durable: true, ui: 'capture-error' },
  'back-durable': { step: 13, durable: true, frontPhoto: true },
  'selfie-durable': { step: 14, durable: true, frontPhoto: true, backPhoto: true },
  'capture-document-preparing': { step: 11, durable: true, capture: { mode: 'document', state: 'preparing' } },
  'capture-document-denied': { step: 11, durable: true, capture: { mode: 'document', state: 'permission-denied' } },
  'capture-document-not-found': { step: 11, durable: true, capture: { mode: 'document', state: 'not-found' } },
  'capture-document-too-small': { step: 11, durable: true, capture: { mode: 'document', state: 'too-small' } },
  'capture-document-clipped': { step: 11, durable: true, capture: { mode: 'document', state: 'clipped' } },
  'capture-document-too-dark': { step: 11, durable: true, capture: { mode: 'document', state: 'too-dark' } },
  'capture-document-blurred': { step: 11, durable: true, capture: { mode: 'document', state: 'blurred' } },
  'capture-document-ready': { step: 11, durable: true, capture: { mode: 'document', state: 'ready' } },
  'capture-document-captured': { step: 11, durable: true, capture: { mode: 'document', state: 'captured' } },
  'capture-document-saving': { step: 11, durable: true, capture: { mode: 'document', state: 'saving' } },
  'capture-document-durable': { step: 11, durable: true, capture: { mode: 'document', state: 'durable' } },
  'capture-document-save-failure': { step: 11, durable: true, capture: { mode: 'document', state: 'save-failure' } },
  'capture-selfie-preparing': { step: 14, durable: true, frontPhoto: true, backPhoto: true, capture: { mode: 'selfie', state: 'preparing' } },
  'capture-selfie-live': { step: 14, durable: true, frontPhoto: true, backPhoto: true, capture: { mode: 'selfie', state: 'live' } },
  'capture-selfie-no-face': { step: 14, durable: true, frontPhoto: true, backPhoto: true, capture: { mode: 'selfie', state: 'no-face' } },
  'capture-selfie-too-far': { step: 14, durable: true, frontPhoto: true, backPhoto: true, capture: { mode: 'selfie', state: 'too-far' } },
  'capture-selfie-too-close': { step: 14, durable: true, frontPhoto: true, backPhoto: true, capture: { mode: 'selfie', state: 'too-close' } },
  'capture-selfie-off-center': { step: 14, durable: true, frontPhoto: true, backPhoto: true, capture: { mode: 'selfie', state: 'off-center' } },
  'capture-selfie-multiple': { step: 14, durable: true, frontPhoto: true, backPhoto: true, capture: { mode: 'selfie', state: 'multiple' } },
  'capture-selfie-dark': { step: 14, durable: true, frontPhoto: true, backPhoto: true, capture: { mode: 'selfie', state: 'dark' } },
  'capture-selfie-ready': { step: 14, durable: true, frontPhoto: true, backPhoto: true, capture: { mode: 'selfie', state: 'ready' } },
  'capture-selfie-captured': { step: 14, durable: true, frontPhoto: true, backPhoto: true, capture: { mode: 'selfie', state: 'captured' } },
  'capture-selfie-saving': { step: 14, durable: true, frontPhoto: true, backPhoto: true, capture: { mode: 'selfie', state: 'saving' } },
  'capture-selfie-durable': { step: 14, durable: true, frontPhoto: true, backPhoto: true, capture: { mode: 'selfie', state: 'durable' } },
  'capture-selfie-failure': { step: 14, durable: true, frontPhoto: true, backPhoto: true, capture: { mode: 'selfie', state: 'save-failure' } },
  'address': { step: 15, durable: true, allDocuments: true },
  'review': { step: 16, durable: true, allDocuments: true, complete: true },
  'consent': { step: 17, durable: true, allDocuments: true, complete: true },
  'submitting': { step: 17, durable: true, allDocuments: true, complete: true, ui: 'submitting' },
  'submit-failed': { step: 17, durable: true, allDocuments: true, complete: true, ui: 'submit-error' },
  'completion': { step: 17, durable: true, allDocuments: true, complete: true, ui: 'completion' },
})

const canUseUxAcceptanceHarness = (nodeEnv) => nodeEnv !== 'production'
const getUxAcceptanceScenario = (name, nodeEnv) => canUseUxAcceptanceHarness(nodeEnv) ? SCENARIOS[name] || null : null

export { SCENARIOS, canUseUxAcceptanceHarness, getUxAcceptanceScenario }
